// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package csm provides the client and types for making API
// requests to Amazon Client-Side Monitoring.
//
// See https://docs.aws.amazon.com/goto/WebAPI/client-side-monitoring-2018-10-23 for more information on this service.
//
// See csm package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/csm/
//
// Using the Client
//
// To contact Amazon Client-Side Monitoring with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Amazon Client-Side Monitoring client CSM for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/csm/#New
package csm
