// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT

// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package sdkmetricsdataplane provides the client and types for making API
// requests to AWS SDK Metrics Dataplane.
//
// See https://docs.aws.amazon.com/goto/WebAPI/sdkmetrics-dataplane-2018-10-22 for more information on this service.
//
// See sdkmetricsdataplane package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/sdkmetricsdataplane/
//
// Using the Client
//
// To contact AWS SDK Metrics Dataplane with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the AWS SDK Metrics Dataplane client SDKMetricsDataplane for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/sdkmetricsdataplane/#New
package sdkmetricsdataplane
