// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT

// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package sdkmetricsdataplane

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{}
