// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for awsinstancestorenvmereceiver metrics.
type MetricsConfig struct {
	DiskioInstanceStoreTotalReadBytes                MetricConfig `mapstructure:"diskio_instance_store_total_read_bytes"`
	DiskioInstanceStoreTotalReadOps                  MetricConfig `mapstructure:"diskio_instance_store_total_read_ops"`
	DiskioInstanceStoreTotalReadTime                 MetricConfig `mapstructure:"diskio_instance_store_total_read_time"`
	DiskioInstanceStoreTotalWriteBytes               MetricConfig `mapstructure:"diskio_instance_store_total_write_bytes"`
	DiskioInstanceStoreTotalWriteOps                 MetricConfig `mapstructure:"diskio_instance_store_total_write_ops"`
	DiskioInstanceStoreTotalWriteTime                MetricConfig `mapstructure:"diskio_instance_store_total_write_time"`
	DiskioInstanceStoreVolumePerformanceExceededIops MetricConfig `mapstructure:"diskio_instance_store_volume_performance_exceeded_iops"`
	DiskioInstanceStoreVolumePerformanceExceededTp   MetricConfig `mapstructure:"diskio_instance_store_volume_performance_exceeded_tp"`
	DiskioInstanceStoreVolumeQueueLength             MetricConfig `mapstructure:"diskio_instance_store_volume_queue_length"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DiskioInstanceStoreTotalReadBytes: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreTotalReadOps: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalReadTime: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreTotalWriteBytes: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreTotalWriteOps: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreTotalWriteTime: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreVolumePerformanceExceededIops: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreVolumePerformanceExceededTp: MetricConfig{
			Enabled: false,
		},
		DiskioInstanceStoreVolumeQueueLength: MetricConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for awsinstancestorenvmereceiver resource attributes.
type ResourceAttributesConfig struct {
	Device       ResourceAttributeConfig `mapstructure:"Device"`
	InstanceID   ResourceAttributeConfig `mapstructure:"InstanceId"`
	SerialNumber ResourceAttributeConfig `mapstructure:"SerialNumber"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		Device: ResourceAttributeConfig{
			Enabled: true,
		},
		InstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		SerialNumber: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for awsinstancestorenvmereceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
