// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awsinstancestorenvmereceiver")
	ScopeName = "github.com/aws/amazon-cloudwatch-agent/receiver/awsinstancestorenvmereceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
