version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - gosec
    - misspell
    - nonamedreturns
    - revive
  disable:
    - errcheck
  settings:
    misspell:
      ignore-rules:
        - performancetest
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
        - revive
        path: 'translator/translate/util/*'
        text: 'var-naming: avoid meaningless package names'
issues:
  new-from-rev: 9af4477
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/aws/amazon-cloudwatch-agent
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
