coverage:
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 5% drop from the previous base commit coverage
        threshold: 5%
fixes:
  - "amazon-cloudwatch-agent/::"