// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("postgresql")
	ScopeName = "github.com/aws/amazon-cloudwatch-agent/receiver/postgresqlreceiver"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelBeta
)
