metrics:
  exclude:
    match_type: strict
    metric_names:
      - up
      - scrape_duration_seconds
      - scrape_samples_scraped
      - scrape_series_added
      - scrape_samples_post_metric_relabeling