lint:
  - '**/*.go'
  - '**/*.sh'
  - '.golangci.yml'
  - '.github/workflows/PR-build.yml'
  - 'packaging/**'
  - 'go.mod'
  - 'Makefile'

build:
  - 'Makefile'
  - 'go.sum'
  - '!({.github,amazon-cloudwatch-container-insights})/**/*.{yml,yaml}'
  - '.github/workflows/PR-build.yml'
  - '**/*.{go,toml,json,conf}'

scripts:
  - 'scripts/**'
  - '.github/scripts/**'
  - '.github/workflows/PR-test.yml'
  - '.github/workflows/ec2-integration-test.yml'
  - '.github/workflows/test-artifacts.yml'
  - '.github/workflows/PR-build.yml'
