metric_statements:
  - context: resource
    error_mode: propagate
    statements:
      - delete_matching_keys(attributes, "^cloud.*")
      - delete_matching_keys(attributes, "^host.*")
      - delete_matching_keys(attributes, "^os.*")
      - delete_matching_keys(attributes, "^container.*")
      - delete_matching_keys(attributes, "^process.*")
      - delete_matching_keys(attributes, "^service.*")
      - delete_matching_keys(attributes, "^telemetry.*")
