// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT

package ssm

import (
	"context"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/aws/aws-sdk-go-v2/service/ssm/types"
	"github.com/aws/smithy-go"

	configaws "github.com/aws/amazon-cloudwatch-agent/cfg/aws/v2"
	"github.com/aws/amazon-cloudwatch-agent/tool/data"
	"github.com/aws/amazon-cloudwatch-agent/tool/processors"
	"github.com/aws/amazon-cloudwatch-agent/tool/runtime"
	"github.com/aws/amazon-cloudwatch-agent/tool/util"
)

const (
	defaultRetryCount = 1 //total attempts are defaultRetryCount+1
)

var Processor processors.Processor = &processor{}

type processor struct{}

func (p *processor) Process(ctx *runtime.Context, config *data.Config) {
	answer := util.Yes("Do you want to store the config in the SSM parameter store?")
	if !answer {
		return
	}

	serializedConfig := util.ReadConfigFromJsonFile()
	parameterStoreName := determineParameterStoreName(ctx)
	region := determineRegion(ctx)

	var err error
	for i := 0; i <= defaultRetryCount; i++ {
		creds := determineCreds(ctx)
		err = sendConfigToParameterStore(context.Background(), serializedConfig, parameterStoreName, region, creds)
		if err == nil {
			fmt.Printf("Successfully put config to parameter store %s.\n", parameterStoreName)
			return
		}

		var accessDenied *types.AccessDeniedException
		if errors.As(err, &accessDenied) {
			fmt.Printf("Please make sure the creds you used have the right permissions configured for SSM access.\n")
			continue
		}
		var apiErr smithy.APIError
		if errors.As(err, &apiErr) {
			fmt.Printf("Error code: %s, message: %s\n", apiErr.ErrorCode(), apiErr.ErrorMessage())
		}
		break
	}
	fmt.Printf("Error in putting config to parameter store %s: %v\n", parameterStoreName, err)
}

func (p *processor) NextProcessor(*runtime.Context, *data.Config) any {
	return nil
}

func determineCreds(_ *runtime.Context) aws.CredentialsProvider {
	ctx := context.Background()
	var accessKeys []string
	sdkAccessKey, _, sdkCredsProvider := util.SDKCredentials(ctx)
	sdkAccessKeyDesc := ""
	if sdkCredsProvider != nil {
		sdkAccessKeyDesc = sdkAccessKey + "(From SDK)"
		accessKeys = append(accessKeys, sdkAccessKeyDesc)
	}

	fileAccessKey := ""
	fileAccessKeyDesc := ""
	fileCredentialsProvider := configaws.RefreshableSharedCredentialsProvider{
		Profile:      "AmazonCloudWatchAgent",
		ExpiryWindow: 10 * time.Minute,
	}
	fileCreds, err := fileCredentialsProvider.Retrieve(ctx)
	if err == nil {
		fileAccessKey = fileCreds.AccessKeyID
		fileAccessKeyDesc = fileAccessKey + "(From Profile: AmazonCloudWatchAgent)"
		accessKeys = append(accessKeys, fileAccessKeyDesc)
	}

	if len(accessKeys) > 0 {
		accessKeys = append(accessKeys, "Other")

		answer := util.Choice("Which AWS credential should be used to send json config to parameter store?", 1, accessKeys)
		if answer == sdkAccessKeyDesc {
			return sdkCredsProvider
		} else if answer == fileAccessKeyDesc {
			return fileCredentialsProvider
		}
	}
	return askCreds()
}

func askCreds() aws.CredentialsProvider {
	accessKey := util.Ask("Please provide credentials to upload the json config file to parameter store.\nAWS Access Key:")
	secretKey := util.Ask("AWS Secret Key:")
	return credentials.NewStaticCredentialsProvider(accessKey, secretKey, "")
}

func determineParameterStoreName(ctx *runtime.Context) string {
	defaultParameterStoreName := "AmazonCloudWatch-" + ctx.OsParameter
	parameterStoreName := util.AskWithDefault("What parameter store name do you want to use to store your config? (Use 'AmazonCloudWatch-' prefix if you use our managed AWS policy)", defaultParameterStoreName)
	return parameterStoreName
}

func determineRegion(ctx *runtime.Context) string {
	var region string
	if !ctx.IsOnPrem {
		region = util.DefaultEC2Region(context.Background())
	} else {
		region = util.SDKRegionWithProfile(context.Background(), "AmazonCloudWatchAgent")
	}
	if region == "" {
		region = "us-east-1"
	}
	region = util.AskWithDefault("Which region do you want to store the config in the parameter store?", region)
	return region
}

func sendConfigToParameterStore(ctx context.Context, configValue, parameterStoreName, region string, credsProvider aws.CredentialsProvider) error {
	opts := []func(*config.LoadOptions) error{
		config.WithRegion(region),
	}

	if credsProvider != nil {
		opts = append(opts, config.WithCredentialsProvider(credsProvider))
	}

	cfg, err := config.LoadDefaultConfig(ctx, opts...)
	if err != nil {
		fmt.Printf("Error in creating session:\n %v\n", err)
		return err
	}

	ssmClient := ssm.NewFromConfig(cfg)

	hostName, _ := os.Hostname()
	description := fmt.Sprintf("Generated by wizard on %s at %s", hostName, time.Now().Format(time.RFC1123))

	input := &ssm.PutParameterInput{
		Name:        aws.String(parameterStoreName),
		Value:       aws.String(configValue),
		Description: aws.String(description),
		Overwrite:   aws.Bool(true),
		Type:        types.ParameterTypeString,
	}

	_, err = ssmClient.PutParameter(ctx, input)
	return err
}
