// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT

package flags

import (
	"fmt"

	"github.com/aws/amazon-cloudwatch-agent/tool/cmdwrapper"
)

// this package needs to be separate to keep the binary size of the wizard small

const (
	Command                             = "config-wizard"
	DefaultFilePathWindowsConfiguration = "C:\\Program Files\\Amazon\\SSM\\Plugins\\awsCloudWatch\\AWS.EC2.Windows.CloudWatch.json"
	DefaultFilePathLinuxConfiguration   = "/var/awslogs/etc/awslogs.conf"
)

var WizardFlags = map[string]cmdwrapper.Flag{
	"is-non-interactive-windows-migration": {"isNonInteractiveWindowsMigration", "false", "If true, it will use command line args to bypass the wizard. Default value is false."},
	"is-non-interactive-linux-migration":   {"isNonInteractiveLinuxMigration", "false", "If true, it will do the linux config migration. Default value is false."},
	"traces-only":                          {"tracesOnly", "false", "If true, only trace configuration will be generated"},
	"use-parameter-store":                  {"useParameterStore", "false", "If true, it will use the parameter store for the migrated config storage."},
	"non-interactive-xray-migration":       {"nonInteractiveXrayMigration", "false", "If true, then this is part of non Interactive xray migration tool."},
	"config-file-path":                     {"configFilePath", "", fmt.Sprintf("The path of the old config file. Default is %s on Windows or %s on Linux", DefaultFilePathWindowsConfiguration, DefaultFilePathLinuxConfiguration)},
	"config-output-path":                   {"configOutputPath", "", "Specifies where to write the configuration file generated by the wizard"},
	"parameter-store-name":                 {"parameterStoreName", "", "The parameter store name. Default is AmazonCloudWatch-windows"},
	"parameter-store-region":               {"parameterStoreRegion", "", "The parameter store region. Default is us-east-1"},
}
