transforms:
  - include: jvm.cpu.recent_utilization
    action: update
    new_name: JVMCpuRecentUtilization
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.cpu.time
    action: update
    new_name: JVMCpuTime
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.classes.loaded
    action: update
    new_name: JVMClassLoaded
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.threads.count
    action: update
    new_name: JVMThreadCount
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.memory.nonheap.used
    action: update
    new_name: JVMMemoryNonHeapUsed
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.memory.pool.used_after_last_gc
    action: update
    new_name: JVMMemoryUsedAfterLastGC
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.memory.heap.used
    action: update
    new_name: JVMMemoryHeapUsed
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.memory.pool.used
    action: insert
    new_name: JVMMemoryOldGenUsed
    match_type: regexp
    experimental_match_labels: {"name": ".*Old\\sGen$"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.memory.pool.used
    action: insert
    new_name: JVMMemorySurvivorSpaceUsed
    match_type: regexp
    experimental_match_labels: {"name": ".*Survivor\\sSpace$"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.memory.pool.used
    action: insert
    new_name: JVMMemoryEdenSpaceUsed
    match_type: regexp
    experimental_match_labels: {"name": ".*Eden\\sSpace$"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.gc.collections.elapsed
    action: insert
    new_name: JVMGCDuration
    operations:
    - action: aggregate_labels
      label_set: []
      aggregation_type: sum
    - action: add_label
      new_label: Telemetry.Source
      new_value: RuntimeMetric
  - include: jvm.gc.collections.count
    action: insert
    new_name: JVMGCCount
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.gc.collections.elapsed
    action: insert
    new_name: JVMGCOldGenDuration
    match_type: strict
    experimental_match_labels: {"name": "G1 Old Generation"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.gc.collections.elapsed
    action: insert
    new_name: JVMGCYoungGenDuration
    match_type: strict
    experimental_match_labels: {"name": "G1 Young Generation"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.gc.collections.count
    action: insert
    new_name: JVMGCOldGenCount
    match_type: strict
    experimental_match_labels: {"name": "G1 Old Generation"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: jvm.gc.collections.count
    action: insert
    new_name: JVMGCYoungGenCount
    match_type: strict
    experimental_match_labels: {"name": "G1 Young Generation"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.gc_count$$
    action: insert
    new_name: PythonProcessGCCount
    match_type: regexp
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.gc_count$$
    action: insert
    new_name: PythonProcessGCGen0Count
    match_type: regexp
    experimental_match_labels: { "count": "0" }
    operations:
      - action: aggregate_labels
        label_set: [ ]
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.gc_count$$
    action: insert
    new_name: PythonProcessGCGen1Count
    match_type: regexp
    experimental_match_labels: { "count": "1" }
    operations:
      - action: aggregate_labels
        label_set: [ ]
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.gc_count$$
    action: insert
    new_name: PythonProcessGCGen2Count
    match_type: regexp
    experimental_match_labels: { "count": "2" }
    operations:
      - action: aggregate_labels
        label_set: [ ]
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.thread_count$$
    action: update
    new_name: PythonProcessThreadCount
    match_type: regexp
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.cpu_time$$
    action: update
    new_name: PythonProcessCpuTime
    match_type: regexp
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.cpu\.utilization$$
    action: update
    new_name: PythonProcessCpuUtilization
    match_type: regexp
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.memory$$
    action: insert
    new_name: PythonProcessVMSMemoryUsed
    match_type: regexp
    experimental_match_labels: {"type": "vms"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
  - include: ^process\.runtime\.(.*)\.memory$$
    action: insert
    new_name: PythonProcessRSSMemoryUsed
    match_type: regexp
    experimental_match_labels: {"type": "rss"}
    operations:
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum
      - action: add_label
        new_label: Telemetry.Source
        new_value: RuntimeMetric
