# This Dockerfile can be used for building Windows Server 2019, 2022 Container images.

# Build Container image from msi installer
ARG IMAGE_TAG=ltsc2022
ARG BUILD_IMAGE=mcr.microsoft.com/windows/servercore:$IMAGE_TAG
ARG TARGETARCH=amd64
ARG CONTAINER_CLOUDWATCHAGENT_PATH=C:\\Program\ Files\\Amazon\\AmazonCloudWatchAgent\\

FROM $BUILD_IMAGE

ARG TARGETARCH
ARG CONTAINER_CLOUDWATCHAGENT_PATH

COPY ${TARGETARCH}/amazon-cloudwatch-agent.msi C:\\tmp\\amazon-cloudwatch-agent.msi
RUN msiexec /i C:\\tmp\\amazon-cloudwatch-agent.msi

WORKDIR $CONTAINER_CLOUDWATCHAGENT_PATH

ENV RUN_IN_CONTAINER="True"
ENTRYPOINT ["start-amazon-cloudwatch-agent.exe"]
