exporters:
    awscloudwatch:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        middleware: agenthealth/metrics
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
extensions:
    agenthealth/metrics:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutMetricData
            usage_flags:
                mode: EC2
                region_type: ACJ
    agenthealth/statuscode:
        is_status_code_enabled: true
        is_usage_data_enabled: true
        stats:
            usage_flags:
                mode: EC2
                region_type: ACJ
    entitystore:
        mode: ec2
        region: us-west-2
processors:
    awsentity/resource:
        entity_type: Resource
        platform: ec2
        scrape_datapoint_attribute: true
    cumulativetodelta/hostDeltaMetrics:
        exclude:
            match_type: strict
            metrics:
                - iops_in_progress
                - diskio_iops_in_progress
                - diskio_ebs_volume_queue_length
        include:
            match_type: ""
        initial_value: 2
        max_staleness: 0s
    ec2tagger:
        ec2_instance_tag_keys:
            - AutoScalingGroupName
        ec2_metadata_tags:
            - InstanceId
            - InstanceType
            - ImageId
        imds_retries: 1
        middleware: agenthealth/statuscode
        refresh_tags_interval: 0s
        refresh_volumes_interval: 0s
receivers:
    telegraf_cpu:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_disk:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_diskio:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_mem:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_netstat:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_swap:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
service:
    extensions:
        - agenthealth/metrics
        - agenthealth/statuscode
        - entitystore
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - ec2tagger
                - awsentity/resource
            receivers:
                - telegraf_netstat
                - telegraf_swap
                - telegraf_cpu
                - telegraf_disk
                - telegraf_mem
        metrics/hostDeltaMetrics:
            exporters:
                - awscloudwatch
            processors:
                - cumulativetodelta/hostDeltaMetrics
                - ec2tagger
                - awsentity/resource
            receivers:
                - telegraf_diskio
    telemetry:
        logs:
            encoding: console
            level: info
            output_paths:
                - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
            sampling:
                enabled: true
                initial: 2
                thereafter: 500
                tick: 10s
        metrics:
            level: None
        traces:
            level: None
