exporters:
    awscloudwatch:
        endpoint_override: https://monitoring-fips.us-west-2.amazonaws.com
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 5000
        middleware: agenthealth/metrics
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
        role_arn: metrics_role_arn_value_test
        rollup_dimensions:
            - - ImageId
            - - InstanceId
              - InstanceType
            - - d1
            - []
    awscloudwatchlogs/emf_logs:
        certificate_file_path: ""
        emf_only: true
        endpoint: https://logs-fips.us-west-2.amazonaws.com
        imds_retries: 1
        local_mode: false
        log_group_name: emf/logs/default
        log_retention: 0
        log_stream_name: LOG_STREAM_NAME
        max_retries: 2
        middleware: agenthealth/logs
        no_verify_ssl: false
        num_workers: 8
        profile: ""
        proxy_address: ""
        raw_log: true
        region: us-west-2
        request_timeout_seconds: 30
        resource_arn: ""
        retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_elapsed_time: 5m0s
            max_interval: 30s
            multiplier: 1.5
            randomization_factor: 0.5
        role_arn: log_role_arn_value_test
        sending_queue:
            enabled: true
            num_consumers: 1
            queue_size: 1000
    awsxray:
        certificate_file_path: ""
        endpoint: https://x-ray-endpoint.us-west-2.amazonaws.com
        imds_retries: 1
        index_all_attributes: false
        local_mode: true
        max_retries: 2
        middleware: agenthealth/traces
        no_verify_ssl: true
        num_workers: 1
        profile: ""
        proxy_address: https://proxy.proxy.com
        region: us-west-2
        request_timeout_seconds: 30
        resource_arn: arn:aws:iam::account:resource
        role_arn: trace_role_arn_value_test
        telemetry:
            enabled: true
            include_metadata: true
extensions:
    agenthealth/logs:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutLogEvents
            usage_flags:
                mode: EC2
                region_type: ACJ
    agenthealth/metrics:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutMetricData
            usage_flags:
                mode: EC2
                region_type: ACJ
    agenthealth/traces:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutTraceSegments
            usage_flags:
                mode: EC2
                region_type: ACJ
processors:
    batch/emf_logs:
        metadata_cardinality_limit: 1000
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 1m0s
    batch/xray:
        metadata_cardinality_limit: 1000
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 200ms
    cumulativetodelta/hostDeltaMetrics:
        exclude:
            match_type: strict
            metrics:
                - iops_in_progress
                - diskio_iops_in_progress
        include:
            match_type: ""
        initial_value: 0
        max_staleness: 0s
    ec2tagger:
        ec2_instance_tag_keys:
            - AutoScalingGroupName
        ec2_metadata_tags:
            - InstanceType
            - ImageId
            - InstanceId
        imds_retries: 1
        refresh_interval_seconds: 0s
    transform:
        error_mode: propagate
        log_statements: []
        metric_statements:
            - context: metric
              statements:
                  - set(unit, "unit") where name == "cpu_usage_idle"
                  - set(name, "CPU_USAGE_IDLE") where name == "cpu_usage_idle"
                  - set(unit, "unit") where name == "cpu_usage_nice"
                  - set(unit, "unit") where name == "disk_free"
                  - set(name, "DISK_FREE") where name == "disk_free"
        trace_statements: []
receivers:
    awsxray:
        dialer:
            timeout: "0s"
        endpoint: 0.0.0.0:2001
        proxy_server:
            aws_endpoint: https://x-ray-endpoint.us-west-2.amazonaws.com
            certificate_file_path: ""
            dialer:
                timeout: "0s"
            endpoint: 0.0.0.0:1234
            imds_retries: 1
            local_mode: true
            profile: ""
            proxy_address: https://proxy.proxy.com
            region: us-west-2
            role_arn: trace_role_arn_value_test
            service_name: "xray"
            tls:
                ca_file: ""
                cert_file: ""
                include_system_ca_certs_pool: false
                insecure: true
                insecure_skip_verify: false
                key_file: ""
                max_version: ""
                min_version: ""
                reload_interval: 0s
                server_name_override: ""
        transport: udp
    otlp/traces:
        protocols:
            grpc:
                dialer:
                    timeout: "0s"
                endpoint: 0.0.0.0:1111
                include_metadata: false
                max_concurrent_streams: 0
                max_recv_msg_size_mib: 0
                read_buffer_size: 524288
                transport: tcp
                write_buffer_size: 0
            http:
                endpoint: 0.0.0.0:2222
                include_metadata: false
                logs_url_path: /v1/logs
                max_request_body_size: 0
                metrics_url_path: /v1/metrics
                traces_url_path: /v1/traces
    telegraf_cpu:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_disk:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_diskio:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_mem:
        collection_interval: 1s
        initial_delay: 1s
        timeout: 0s
    telegraf_net:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_netstat:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_processes:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_procstat/1917393364:
        alias_name: /var/run/example1.pid
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_socket_listener:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_statsd:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    telegraf_swap:
        collection_interval: 10s
        initial_delay: 1s
        timeout: 0s
    udplog/emf_logs:
        encoding: utf-8
        id: udp_input
        listen_address: 127.0.0.1:25888
        multiline:
            line_end_pattern: .^
            line_start_pattern: ""
            omit_pattern: false
        operators: []
        retry_on_failure:
            enabled: false
            initial_interval: 0s
            max_elapsed_time: 0s
            max_interval: 0s
        type: udp_input
service:
    extensions:
        - agenthealth/metrics
        - agenthealth/logs
        - agenthealth/traces
    pipelines:
        logs/emf_logs:
            exporters:
                - awscloudwatchlogs/emf_logs
            processors:
                - batch/emf_logs
            receivers:
                - udplog/emf_logs
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - ec2tagger
                - transform
            receivers:
                - telegraf_swap
                - telegraf_processes
                - telegraf_mem
                - telegraf_netstat
                - telegraf_cpu
                - telegraf_statsd
                - telegraf_procstat/1917393364
                - telegraf_socket_listener
                - telegraf_disk
        metrics/hostDeltaMetrics:
            exporters:
                - awscloudwatch
            processors:
                - cumulativetodelta/hostDeltaMetrics
                - ec2tagger
                - transform
            receivers:
                - telegraf_net
                - telegraf_diskio
        traces/xray:
            exporters:
                - awsxray
            processors:
                - batch/xray
            receivers:
                - awsxray
                - otlp/traces
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: console
            level: debug
            output_paths:
                - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
            sampling:
                enabled: true
                initial: 2
                thereafter: 500
                tick: 10s
        metrics:
            address: ""
            level: None
        traces: {}
