[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "1s"
  flush_jitter = "0s"
  hostname = ""
  interval = "60s"
  logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  logtarget = "lumberjack"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  quiet = false
  round_interval = false

[inputs]

  [[inputs.dpdk]]
    device_types = ["ethdev"]
    fieldpass = ["bw_in_allowance_exceeded", "bw_out_allowance_exceeded", "pps_allowance_exceeded", "conntrack_allowance_exceeded", "linklocal_allowance_exceeded", "rx_missed_errors"]
    socket_path = "/var/run/dpdk/rte/dpdk_telemetry.v2"
    [inputs.dpdk.ethdev]
      exclude_commands = ["/ethdev/link_status"]

[outputs]

  [[outputs.cloudwatch]]
