exporters:
    awscloudwatch:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        middleware: agenthealth/metrics
        namespace: CWAgent
        profile: AmazonCloudWatchAgent
        region: us-east-1
        resource_to_telemetry_conversion:
            enabled: true
        role_arn: arn:aws:iam::123456789012:role/OIDCRole
        shared_credential_file: fake-path
extensions:
    agenthealth/metrics:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutMetricData
            usage_flags:
                mode: OP
                region_type: ACJ
    agenthealth/statuscode:
        is_status_code_enabled: true
        is_usage_data_enabled: true
        stats:
            usage_flags:
                mode: OP
                region_type: ACJ
    cloudauth:
        token_dir: /opt/aws/amazon-cloudwatch-agent/var
    entitystore:
        mode: onPremise
        profile: AmazonCloudWatchAgent
        region: us-east-1
        shared_credential_file: fake-path
processors:
    resourcedetection/resourcedetection:
        aks:
            resource_attributes:
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                k8s.cluster.name:
                    enabled: false
        azure:
            resource_attributes:
                azure.resourcegroup.name:
                    enabled: false
                azure.vm.name:
                    enabled: false
                azure.vm.scaleset.name:
                    enabled: false
                azure.vm.size:
                    enabled: false
                cloud.account.id:
                    enabled: false
                cloud.platform:
                    enabled: false
                cloud.provider:
                    enabled: false
                cloud.region:
                    enabled: false
                host.id:
                    enabled: false
                host.name:
                    enabled: false
            tags: []
        consul:
            address: ""
            datacenter: ""
            namespace: ""
            resource_attributes:
                cloud.region:
                    enabled: true
                host.id:
                    enabled: true
                host.name:
                    enabled: true
            token_file: ""
        detectors:
            - env
            - azure
            - gcp
            - system
        docker:
            resource_attributes:
                host.name:
                    enabled: true
                os.type:
                    enabled: true
        ec2:
            fail_on_missing_metadata: false
            max_attempts: 3
            max_backoff: 20s
            resource_attributes:
                cloud.account.id:
                    enabled: false
                cloud.availability_zone:
                    enabled: false
                cloud.platform:
                    enabled: false
                cloud.provider:
                    enabled: false
                cloud.region:
                    enabled: false
                host.id:
                    enabled: false
                host.image.id:
                    enabled: false
                host.name:
                    enabled: false
                host.type:
                    enabled: false
            tags: []
        ecs:
            resource_attributes:
                aws.ecs.cluster.arn:
                    enabled: true
                aws.ecs.launchtype:
                    enabled: true
                aws.ecs.task.arn:
                    enabled: true
                aws.ecs.task.family:
                    enabled: true
                aws.ecs.task.id:
                    enabled: true
                aws.ecs.task.revision:
                    enabled: true
                aws.log.group.arns:
                    enabled: true
                aws.log.group.names:
                    enabled: true
                aws.log.stream.arns:
                    enabled: true
                aws.log.stream.names:
                    enabled: true
                cloud.account.id:
                    enabled: true
                cloud.availability_zone:
                    enabled: true
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                cloud.region:
                    enabled: true
        eks:
            resource_attributes:
                cloud.account.id:
                    enabled: false
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                k8s.cluster.name:
                    enabled: false
        elasticbeanstalk:
            resource_attributes:
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                deployment.environment:
                    enabled: true
                service.instance.id:
                    enabled: true
                service.version:
                    enabled: true
        gcp:
            resource_attributes:
                cloud.account.id:
                    enabled: true
                cloud.availability_zone:
                    enabled: true
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                cloud.region:
                    enabled: true
                faas.id:
                    enabled: true
                faas.instance:
                    enabled: true
                faas.name:
                    enabled: true
                faas.version:
                    enabled: true
                gcp.cloud_run.job.execution:
                    enabled: true
                gcp.cloud_run.job.task_index:
                    enabled: true
                gcp.gce.instance.hostname:
                    enabled: false
                gcp.gce.instance.name:
                    enabled: false
                gcp.gce.instance_group_manager.name:
                    enabled: true
                gcp.gce.instance_group_manager.region:
                    enabled: true
                gcp.gce.instance_group_manager.zone:
                    enabled: true
                host.id:
                    enabled: true
                host.name:
                    enabled: true
                host.type:
                    enabled: true
                k8s.cluster.name:
                    enabled: true
        heroku:
            resource_attributes:
                cloud.provider:
                    enabled: true
                heroku.app.id:
                    enabled: true
                heroku.dyno.id:
                    enabled: true
                heroku.release.commit:
                    enabled: true
                heroku.release.creation_timestamp:
                    enabled: true
                service.instance.id:
                    enabled: true
                service.name:
                    enabled: true
                service.version:
                    enabled: true
        idle_conn_timeout: 1m30s
        k8snode:
            auth_type: serviceAccount
            context: ""
            kube_config_path: ""
            node_from_env_var: ""
            resource_attributes:
                k8s.node.name:
                    enabled: true
                k8s.node.uid:
                    enabled: true
        kubeadm:
            auth_type: serviceAccount
            context: ""
            kube_config_path: ""
            resource_attributes:
                k8s.cluster.name:
                    enabled: true
                k8s.cluster.uid:
                    enabled: true
        lambda:
            resource_attributes:
                aws.log.group.names:
                    enabled: true
                aws.log.stream.names:
                    enabled: true
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                cloud.region:
                    enabled: true
                faas.instance:
                    enabled: true
                faas.max_memory:
                    enabled: true
                faas.name:
                    enabled: true
                faas.version:
                    enabled: true
        max_idle_conns: 100
        openshift:
            address: ""
            resource_attributes:
                cloud.platform:
                    enabled: true
                cloud.provider:
                    enabled: true
                cloud.region:
                    enabled: true
                k8s.cluster.name:
                    enabled: true
            tls: {}
            token: ""
        override: false
        system:
            resource_attributes:
                host.arch:
                    enabled: false
                host.cpu.cache.l2.size:
                    enabled: false
                host.cpu.family:
                    enabled: false
                host.cpu.model.id:
                    enabled: false
                host.cpu.model.name:
                    enabled: false
                host.cpu.stepping:
                    enabled: false
                host.cpu.vendor.id:
                    enabled: false
                host.id:
                    enabled: false
                host.ip:
                    enabled: false
                host.mac:
                    enabled: false
                host.name:
                    enabled: true
                os.description:
                    enabled: false
                os.type:
                    enabled: true
                os.version:
                    enabled: false
        timeout: 5s
receivers:
    telegraf_mem:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
service:
    extensions:
        - agenthealth/metrics
        - agenthealth/statuscode
        - entitystore
        - cloudauth
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - resourcedetection/resourcedetection
            receivers:
                - telegraf_mem
    telemetry:
        logs:
            encoding: console
            level: info
            output_paths:
                - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
            sampling:
                enabled: true
                initial: 2
                thereafter: 500
                tick: 10s
        metrics:
            level: None
        traces:
            level: None
