exporters:
    awscloudwatch:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        middleware: agenthealth/metrics
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
extensions:
    agenthealth/metrics:
        is_usage_data_enabled: true
        stats:
            operations:
                - PutMetricData
            usage_flags:
                mode: EC2
                region_type: ACJ
    agenthealth/statuscode:
        is_status_code_enabled: true
        is_usage_data_enabled: true
        stats:
            usage_flags:
                mode: EC2
                region_type: ACJ
    entitystore:
        mode: ec2
        region: us-west-2
    opamp:
        agent_description:
            non_identifying_attributes:
                agent.name: Cloudwatch Agent
                description: OpAMP Extension Enabled in Cloudwatch Agent
                foo: bar
        capabilities:
            reports_available_components: true
            reports_effective_config: true
            reports_health: true
        instance_uid: 123e4567-e89b-12d3-a456-426614174000
        ppid: 12345
        ppid_poll_interval: 5s
        server:
            http:
                polling_interval: 10s
processors:
    awsentity/resource:
        entity_type: Resource
        platform: ec2
receivers:
    telegraf_disk:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
    telegraf_mem:
        collection_interval: 1m0s
        initial_delay: 1s
        timeout: 0s
service:
    extensions:
        - agenthealth/metrics
        - agenthealth/statuscode
        - entitystore
        - opamp
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - awsentity/resource
            receivers:
                - telegraf_mem
                - telegraf_disk
    telemetry:
        logs:
            encoding: console
            level: info
            output_paths:
                - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
            sampling:
                enabled: true
                initial: 2
                thereafter: 500
                tick: 10s
        metrics:
            level: None
        traces:
            level: None
