exporters:
    prometheusremotewrite/amp:
        add_metric_suffixes: true
        auth:
            authenticator: sigv4auth
        compression: ""
        disable_keep_alives: false
        endpoint: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-12345/api/v1/remote_write
        export_created_metric:
            enabled: false
        http2_ping_timeout: 0s
        http2_read_idle_timeout: 0s
        max_batch_size_bytes: 3000000
        namespace: ""
        proxy_url: ""
        read_buffer_size: 0
        remote_write_queue:
            enabled: true
            num_consumers: 5
            queue_size: 10000
        resource_to_telemetry_conversion:
            clear_after_copy: true
            enabled: true
        retry_on_failure:
            enabled: true
            initial_interval: 50ms
            max_elapsed_time: 5m0s
            max_interval: 30s
            multiplier: 1.5
            randomization_factor: 0.5
        send_metadata: false
        target_info:
            enabled: true
        timeout: 5s
        tls:
            ca_file: ""
            cert_file: ""
            include_system_ca_certs_pool: false
            insecure: false
            insecure_skip_verify: false
            key_file: ""
            max_version: ""
            min_version: ""
            reload_interval: 0s
            server_name_override: ""
        write_buffer_size: 524288
extensions:
    sigv4auth:
        assume_role:
            sts_region: us-west-2
        region: us-west-2
processors:
    batch/prometheus/amp:
        metadata_cardinality_limit: 1000
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 1m0s
receivers:
    prometheus:
        config:
            alertingconfig: {}
            globalconfig:
                bodysizelimit: 0B
                evaluationinterval: 1m
                keepdroppedtargets: 0
                labellimit: 0
                labelnamelengthlimit: 0
                labelvaluelengthlimit: 0
                querylogfile: ""
                samplelimit: 0
                scrapeinterval: 5m
                scrapeprotocols:
                    - OpenMetricsText1.0.0
                    - OpenMetricsText0.0.1
                    - PrometheusText0.0.4
                scrapetimeout: 5s
                targetlimit: 0
            scrapeconfigs:
                - bodysizelimit: 0B
                  enablecompression: true
                  honorlabels: false
                  honortimestamps: true
                  httpclientconfig:
                    bearertoken: null
                    bearertokenfile: ""
                    enablehttp2: true
                    followredirects: true
                    proxyconfig:
                        noproxy: ""
                        proxyfromenvironment: false
                        proxyurl: {}
                    tlsconfig:
                        ca: ""
                        cafile: ""
                        caref: ""
                        cert: ""
                        certfile: ""
                        certref: ""
                        insecureskipverify: false
                        key: null
                        keyfile: ""
                        keyref: ""
                        maxversion: TLS13
                        minversion: TLS10
                        servername: ""
                  jobname: cwagent-ecs-file-sd-config
                  keepdroppedtargets: 0
                  labellimit: 0
                  labelnamelengthlimit: 0
                  labelvaluelengthlimit: 0
                  metricspath: /metrics
                  nativehistogrambucketlimit: 0
                  nativehistogramminbucketfactor: 0
                  samplelimit: 10000
                  scheme: http
                  scrapeclassichistograms: false
                  scrapeinterval: 5m
                  scrapeprotocols:
                    - OpenMetricsText1.0.0
                    - OpenMetricsText0.0.1
                    - PrometheusText0.0.4
                  scrapetimeout: 5s
                  servicediscoveryconfigs:
                    - files:
                        - {ecsSdFileName}
                      refreshinterval: 5m
                  targetlimit: 0
                  tracktimestampsstaleness: false
            storageconfig: {}
            tracingconfig:
                clienttype: ""
                compression: ""
                endpoint: ""
                insecure: false
                samplingfraction: 0
                timeout: 0s
                tlsconfig:
                    ca: ""
                    cafile: ""
                    caref: ""
                    cert: ""
                    certfile: ""
                    certref: ""
                    insecureskipverify: false
                    key: null
                    keyfile: ""
                    keyref: ""
                    maxversion: TLS13
                    minversion: TLS10
                    servername: ""
        report_extra_scrape_metrics: false
        start_time_metric_regex: ""
        trim_metric_suffixes: false
        use_start_time_metric: false
service:
    extensions:
        - sigv4auth
    pipelines:
        metrics/prometheus:
            exporters:
                - prometheusremotewrite/amp
            processors:
                - batch/prometheus/amp
            receivers:
                - prometheus
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: console
            level: info
            output_paths:
                - /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log
            sampling:
                enabled: true
                initial: 2
                thereafter: 500
                tick: 10s
        metrics:
            address: ""
            level: None
        traces: {}
