config:
  global:
    scrape_interval: 5m
    scrape_timeout: 5s
  scrape_configs:
    - job_name: cwagent-ecs-file-sd-config
      sample_limit: 10000
      file_sd_configs:
        - files: [ '{ecsSdFileName}' ]
target_allocator:
  endpoint: http://target-allocator-service:80
  interval: 30s
