global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: kubernetes-service-endpoints
    kubernetes_sd_configs:
      - role: endpoints
    metric_relabel_configs:
      - action: drop
        regex: go_gc_duration_seconds.*
        source_labels:
          - __name__
      - regex: haproxy_frontend.+;(.+)
        replacement: $1
        source_labels:
          - __name__
          - proxy
        target_label: frontend
      - regex: haproxy_server.+;(.+)
        replacement: $1
        source_labels:
          - __name__
          - proxy
        target_label: backend
      - regex: haproxy_backend.+;(.+)
        replacement: $1
        source_labels:
          - __name__
          - proxy
        target_label: backend
      - action: labeldrop
        regex: proxy
    relabel_configs:
      - action: keep
        regex: true
        source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
          - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::d+)?;(d+)
        replacement: $1:$2
        source_labels:
          - __address__
          - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: Namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_service_name
        target_label: Service
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: kubernetes_node
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod_name
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container_name
    sample_limit: 10000

  - job_name: kubernetes-apiservers
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: keep
        regex: kubernetes;https
        source_labels:
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: Namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_service_name
        target_label: Service
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
