exporters:
    nop: {}
extensions:
    entitystore:
      mode: "ec2"
      region: us-west-2
receivers:
    nop: {}
service:
    extensions:
      - entitystore
    pipelines:
        metrics/nop:
            exporters:
                - nop
            processors: []
            receivers:
                - nop
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: console
            level: info
            output_paths:
              - c:\ProgramData\Amazon\AmazonCloudWatchAgent\Logs\amazon-cloudwatch-agent.log
            sampling:
              enabled: true
              initial: 2
              thereafter: 500
              tick: 10s
        metrics:
            address: ""
            level: None
        traces: { }