// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetDevice sets provided value as "device" attribute.
func (rb *ResourceBuilder) SetDevice(val string) {
	if rb.config.Device.Enabled {
		rb.res.Attributes().PutStr("device", val)
	}
}

// SetDeviceType sets provided value as "device_type" attribute.
func (rb *ResourceBuilder) SetDeviceType(val string) {
	if rb.config.DeviceType.Enabled {
		rb.res.Attributes().PutStr("device_type", val)
	}
}

// SetInstanceID sets provided value as "instance_id" attribute.
func (rb *ResourceBuilder) SetInstanceID(val string) {
	if rb.config.InstanceID.Enabled {
		rb.res.Attributes().PutStr("instance_id", val)
	}
}

// SetSerialNumber sets provided value as "serial_number" attribute.
func (rb *ResourceBuilder) SetSerialNumber(val string) {
	if rb.config.SerialNumber.Enabled {
		rb.res.Attributes().PutStr("serial_number", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
