// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awsebsnvmereceiver")
	ScopeName = "github.com/aws/amazon-cloudwatch-agent/receiver/awsebsnvmereceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
