// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for awsnvmereceiver metrics.
type MetricsConfig struct {
	DiskioEbsEc2InstancePerformanceExceededIops      MetricConfig `mapstructure:"diskio_ebs_ec2_instance_performance_exceeded_iops"`
	DiskioEbsEc2InstancePerformanceExceededTp        MetricConfig `mapstructure:"diskio_ebs_ec2_instance_performance_exceeded_tp"`
	DiskioEbsTotalReadBytes                          MetricConfig `mapstructure:"diskio_ebs_total_read_bytes"`
	DiskioEbsTotalReadOps                            MetricConfig `mapstructure:"diskio_ebs_total_read_ops"`
	DiskioEbsTotalReadTime                           MetricConfig `mapstructure:"diskio_ebs_total_read_time"`
	DiskioEbsTotalWriteBytes                         MetricConfig `mapstructure:"diskio_ebs_total_write_bytes"`
	DiskioEbsTotalWriteOps                           MetricConfig `mapstructure:"diskio_ebs_total_write_ops"`
	DiskioEbsTotalWriteTime                          MetricConfig `mapstructure:"diskio_ebs_total_write_time"`
	DiskioEbsVolumePerformanceExceededIops           MetricConfig `mapstructure:"diskio_ebs_volume_performance_exceeded_iops"`
	DiskioEbsVolumePerformanceExceededTp             MetricConfig `mapstructure:"diskio_ebs_volume_performance_exceeded_tp"`
	DiskioEbsVolumeQueueLength                       MetricConfig `mapstructure:"diskio_ebs_volume_queue_length"`
	DiskioInstanceStoreTotalReadBytes                MetricConfig `mapstructure:"diskio_instance_store_total_read_bytes"`
	DiskioInstanceStoreTotalReadOps                  MetricConfig `mapstructure:"diskio_instance_store_total_read_ops"`
	DiskioInstanceStoreTotalReadTime                 MetricConfig `mapstructure:"diskio_instance_store_total_read_time"`
	DiskioInstanceStoreTotalWriteBytes               MetricConfig `mapstructure:"diskio_instance_store_total_write_bytes"`
	DiskioInstanceStoreTotalWriteOps                 MetricConfig `mapstructure:"diskio_instance_store_total_write_ops"`
	DiskioInstanceStoreTotalWriteTime                MetricConfig `mapstructure:"diskio_instance_store_total_write_time"`
	DiskioInstanceStoreVolumePerformanceExceededIops MetricConfig `mapstructure:"diskio_instance_store_volume_performance_exceeded_iops"`
	DiskioInstanceStoreVolumePerformanceExceededTp   MetricConfig `mapstructure:"diskio_instance_store_volume_performance_exceeded_tp"`
	DiskioInstanceStoreVolumeQueueLength             MetricConfig `mapstructure:"diskio_instance_store_volume_queue_length"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DiskioEbsEc2InstancePerformanceExceededIops: MetricConfig{
			Enabled: true,
		},
		DiskioEbsEc2InstancePerformanceExceededTp: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalReadBytes: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalReadOps: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalReadTime: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalWriteBytes: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalWriteOps: MetricConfig{
			Enabled: true,
		},
		DiskioEbsTotalWriteTime: MetricConfig{
			Enabled: true,
		},
		DiskioEbsVolumePerformanceExceededIops: MetricConfig{
			Enabled: true,
		},
		DiskioEbsVolumePerformanceExceededTp: MetricConfig{
			Enabled: true,
		},
		DiskioEbsVolumeQueueLength: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalReadBytes: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalReadOps: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalReadTime: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalWriteBytes: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalWriteOps: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreTotalWriteTime: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreVolumePerformanceExceededIops: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreVolumePerformanceExceededTp: MetricConfig{
			Enabled: true,
		},
		DiskioInstanceStoreVolumeQueueLength: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for awsnvmereceiver resource attributes.
type ResourceAttributesConfig struct {
	Device       ResourceAttributeConfig `mapstructure:"device"`
	DeviceType   ResourceAttributeConfig `mapstructure:"device_type"`
	InstanceID   ResourceAttributeConfig `mapstructure:"instance_id"`
	SerialNumber ResourceAttributeConfig `mapstructure:"serial_number"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		Device: ResourceAttributeConfig{
			Enabled: true,
		},
		DeviceType: ResourceAttributeConfig{
			Enabled: true,
		},
		InstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		SerialNumber: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for awsnvmereceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
