// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awsnvmereceiver")
	ScopeName = "github.com/aws/amazon-cloudwatch-agent/receiver/awsnvmereceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
