// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetDevice("device-val")
			rb.SetDeviceType("device_type-val")
			rb.SetInstanceID("instance_id-val")
			rb.SetSerialNumber("serial_number-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 4, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 4, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("device")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "device-val", val.Str())
			}
			val, ok = res.Attributes().Get("device_type")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "device_type-val", val.Str())
			}
			val, ok = res.Attributes().Get("instance_id")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "instance_id-val", val.Str())
			}
			val, ok = res.Attributes().Get("serial_number")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "serial_number-val", val.Str())
			}
		})
	}
}
