# Default CloudWatch Agent OpAMP Supervisor Configuration
# Packaged with CloudWatch Agent installation

server:
  endpoint: wss://127.0.0.1:4320/v1/opamp
  tls:
    insecure_skip_verify: true

capabilities:
  reports_effective_config: true
  reports_health: true
  reports_own_metrics: true
  accepts_remote_config: true
  reports_remote_config: true
  accepts_restart_command: true

agent:
  executable: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent
  config_files:
    - /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.yaml
storage:
  directory: /opt/aws/amazon-cloudwatch-agent/logs