# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: build-and-test-mac
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/build-*'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  mac-unittest:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.15.15

      - name: Cache build output
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: go-build-v1-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: make test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true

      - name: Build
        run: make build