# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: AMI Monthly Resources Cleaner

on:
  schedule:
    - cron: "0 0 1 * *" # Run on the first day of every month
  workflow_dispatch:

jobs:
  clean-ami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Clean old ami
        run: go run ./integration/clean/clean_ami/clean_ami.go --tags=clean