name: Close stalled issues and PRs
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    if: github.repository == 'aws/amazon-cloudwatch-agent'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue-message: Closing this because it has stalled. Feel free to reopen if this issue is still relevant, or to ping the collaborator who labeled it stalled if you have any questions.
          
          # Do not close PRs
          days-before-pr-close: -1
          # close-pr-message: Closing this because it has stalled. Feel free to reopen if this PR is still relevant, or to ping the collaborator who labelled it stalled if you have any questions.
          
          days-before-pr-stale: 7
          days-before-issue-stale: 90
          days-before-issue-close: 30

          # Do not close things assigned to milestones
          exempt-all-milestones: true