# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Reusable EC2 Integration Test

env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  KEY_NAME: ${{ secrets.KEY_NAME }}
  TERRAFORM_AWS_ASSUME_ROLE_DURATION: 14400 # 4 hours

on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: string
      test_repo_name:
        required: true
        type: string
      test_repo_url:
        required: true
        type: string
      test_repo_branch:
        required: true
        type: string
      test_dir:
        required: true
        type: string
      job_id:
        required: true
        type: string
      test_props:
        required: true
        type: string
      localstack_host:
        type: string
      region:
        type: string
      terraform_assume_role:
        type: string
      is_selinux_test:
        type: boolean
      is_onprem_test:
        type: boolean
      s3_integration_bucket:
        type: string
    secrets:
      AWS_PRIVATE_KEY:
        required: false
      KEY_NAME:
        required: false

jobs:
  EC2IntegrationTest:
    name: ${{matrix.arrays.testName}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arrays: ${{ fromJson(inputs.test_props) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: ${{inputs.test_repo_name}}
          ref: ${{inputs.test_repo_branch}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ inputs.terraform_assume_role }}
          aws-region: ${{inputs.region}}
          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}

      - name: Echo Test Info
        env:
          MATRIX_OS: ${{ matrix.arrays.os }}
          MATRIX_ARC: ${{ matrix.arrays.arc }}
          MATRIX_TEST_DIR: ${{ matrix.arrays.test_dir }}
          INPUT_LOCALSTACK_HOST: ${{ inputs.localstack_host }}
        run: |
          echo "run cache_if_success os $MATRIX_OS arc $MATRIX_ARC test dir $MATRIX_TEST_DIR"
          echo "localstack input $INPUT_LOCALSTACK_HOST"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform apply
        id: terraform_apply
        continue-on-error: true
        timeout-minutes: 60
        env:
          MATRIX_TERRAFORM_DIR: ${{ matrix.arrays.terraform_dir }}
          INPUT_TEST_DIR: ${{ inputs.test_dir }}
          MATRIX_AGENT_START: ${{ matrix.arrays.agentStartCommand }}
          MATRIX_AMI: ${{ matrix.arrays.ami }}
          MATRIX_ARC: ${{ matrix.arrays.arc }}
          MATRIX_BINARY_NAME: ${{ matrix.arrays.binaryName }}
          MATRIX_CA_CERT_PATH: ${{ matrix.arrays.caCertPath }}
          INPUT_BUILD_ID: ${{ inputs.build_id }}
          MATRIX_INSTANCE_TYPE: ${{ matrix.arrays.instanceType }}
          MATRIX_EXCLUDED_TESTS: ${{ matrix.arrays.excludedTests }}
          INPUT_TEST_REPO_URL: ${{ inputs.test_repo_url }}
          INPUT_TEST_REPO_BRANCH: ${{ inputs.test_repo_branch }}
          MATRIX_INSTALL_AGENT: ${{ matrix.arrays.installAgentCommand }}
          INPUT_IS_SELINUX_TEST: ${{ inputs.is_selinux_test }}
          MATRIX_SELINUX_BRANCH: ${{ matrix.arrays.selinux_branch }}
          INPUT_LOCALSTACK_HOST: ${{ inputs.localstack_host }}
          INPUT_PLUGINS: ${{ github.event.inputs.plugins }}
          INPUT_REGION: ${{ inputs.region }}
          INPUT_S3_BUCKET: ${{ inputs.s3_integration_bucket }}
          MATRIX_TEST_DIR: ${{ matrix.arrays.test_dir }}
          MATRIX_OS: ${{ matrix.arrays.os }}
          INPUT_IS_ONPREM_TEST: ${{ inputs.is_onprem_test }}
          MATRIX_USERNAME: ${{ matrix.arrays.username }}
        run: |
          if [ -n "$MATRIX_TERRAFORM_DIR" ]; then
            cd "$MATRIX_TERRAFORM_DIR"
          else
            cd "$INPUT_TEST_DIR"
          fi

          terraform init
          if terraform apply --auto-approve \
            -var="agent_start=$MATRIX_AGENT_START" \
            -var="ami=$MATRIX_AMI" \
            -var="arc=$MATRIX_ARC" \
            -var="binary_name=$MATRIX_BINARY_NAME" \
            -var="ca_cert_path=$MATRIX_CA_CERT_PATH" \
            -var="cwa_github_sha=$INPUT_BUILD_ID" \
            -var="ec2_instance_type=$MATRIX_INSTANCE_TYPE" \
            -var="excluded_tests='$MATRIX_EXCLUDED_TESTS'" \
            -var="github_test_repo=$INPUT_TEST_REPO_URL" \
            -var="github_test_repo_branch=$INPUT_TEST_REPO_BRANCH" \
            -var="install_agent=$MATRIX_INSTALL_AGENT" \
            -var="is_selinux_test=$INPUT_IS_SELINUX_TEST" \
            -var="selinux_branch=$MATRIX_SELINUX_BRANCH" \
            -var="local_stack_host_name=$INPUT_LOCALSTACK_HOST" \
            -var="plugin_tests='$INPUT_PLUGINS'" \
            -var="region=$INPUT_REGION" \
            -var="s3_bucket=$INPUT_S3_BUCKET" \
            -var="ssh_key_name=$KEY_NAME" \
            -var="ssh_key_value=$PRIVATE_KEY" \
            -var="test_dir=$MATRIX_TEST_DIR" \
            -var="test_name=$MATRIX_OS" \
            -var="is_onprem=$INPUT_IS_ONPREM_TEST" \
            -var="user=$MATRIX_USERNAME"; then
            terraform destroy -var="region=$INPUT_REGION" -var="ami=$MATRIX_AMI" -auto-approve
          else
            terraform destroy -var="region=$INPUT_REGION" -var="ami=$MATRIX_AMI" -auto-approve && exit 1
          fi
      
      - name: "[WIP] ✅ Passed"
        if: steps.terraform_apply.outcome == 'success' && matrix.arrays.wip
        run: echo "::notice::WIP test passed"

      - name: "[WIP] ⚠️ Failed (Overruled)"
        if: steps.terraform_apply.outcome == 'failure' && matrix.arrays.wip
        run: |
          echo "::warning::WIP test failed but allowed to continue"
          echo "### ⚠️ WIP Test Failed (Overruled)" >> $GITHUB_STEP_SUMMARY

      - name: Fail if not WIP
        if: steps.terraform_apply.outcome == 'failure' && !matrix.arrays.wip
        run: exit 1
      
      #This is here just in case workflow cancel
      - name: Terraform destroy
        if: ${{ cancelled() || failure() || steps.terraform_apply.outcome == 'failure' }}
        env:
          MATRIX_TERRAFORM_DIR: ${{ matrix.arrays.terraform_dir }}
          INPUT_TEST_DIR: ${{ inputs.test_dir }}
          INPUT_REGION: ${{ inputs.region }}
          MATRIX_AMI: ${{ matrix.arrays.ami }}
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          max_attempts: 2
          timeout_minutes: 8
          retry_wait_seconds: 5
          command: |
            if [ -n "$MATRIX_TERRAFORM_DIR" ]; then
              cd "$MATRIX_TERRAFORM_DIR"
            else
              cd "$INPUT_TEST_DIR"
            fi

            terraform destroy -lock-timeout=5m -var="region=$INPUT_REGION" -var="ami=$MATRIX_AMI" --auto-approve
