# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: EFA EC2 Integration Test

env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  KEY_NAME: ${{ secrets.KEY_NAME }}
  S3_INTEGRATION_BUCKET: ${{ vars.S3_INTEGRATION_BUCKET }}
  TERRAFORM_AWS_ASSUME_ROLE: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
  TERRAFORM_AWS_ASSUME_ROLE_DURATION: 14400
  CWA_GITHUB_TEST_REPO_NAME: "aws/amazon-cloudwatch-agent-test"
  CWA_GITHUB_TEST_REPO_URL: "https://github.com/aws/amazon-cloudwatch-agent-test.git"

on:
  workflow_dispatch:
    inputs:
      build_sha:
        description: 'Build SHA to test. Leave empty to build from current branch'
        type: string
        default: ''
      test_repo_branch:
        description: 'Branch of amazon-cloudwatch-agent-test repo'
        type: string
        default: 'main'
      ec2_instance_type:
        description: 'EFA-capable EC2 instance type'
        type: string
        default: 'c5n.9xlarge'
      ami:
        description: 'AMI name filter'
        type: string
        default: 'cloudwatch-agent-integration-test-al2023*'

jobs:
  BuildAndUpload:
    name: 'BuildAndUpload'
    runs-on: ubuntu-latest
    if: ${{ inputs.build_sha == '' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Set up Go 1.x
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: ~1.25.8
          cache: false

      - name: Install rpm
        run: sudo apt install rpm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2
          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}

      - name: Build binaries
        run: make amazon-cloudwatch-agent-linux

      - name: Upload to S3
        run: aws s3 cp build/bin s3://${S3_INTEGRATION_BUCKET}/integration-test/binary/${GITHUB_SHA} --recursive

  EfaEC2IntegrationTest:
    name: 'EfaEC2IntegrationTest'
    needs: [BuildAndUpload]
    if: always() && (needs.BuildAndUpload.result == 'success' || needs.BuildAndUpload.result == 'skipped')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: ${{ env.CWA_GITHUB_TEST_REPO_NAME }}
          ref: ${{ inputs.test_repo_branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2
          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.12.0

      - name: Verify Terraform version
        run: terraform --version

      # nick-fields/retry@v2 starts at base dir
      - name: Terraform apply
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_wait_seconds: 5
          command: |
            cd terraform/ec2/efa
            terraform init
            if terraform apply --auto-approve \
              -var="ssh_key_value=${PRIVATE_KEY}" \
              -var="github_test_repo=${CWA_GITHUB_TEST_REPO_URL}" \
              -var="test_name=al2023" \
              -var="cwa_github_sha=${{ inputs.build_sha || github.sha }}" \
              -var="install_agent=go run ./install/install_agent.go rpm" \
              -var="github_test_repo_branch=${{ inputs.test_repo_branch }}" \
              -var="ec2_instance_type=${{ inputs.ec2_instance_type }}" \
              -var="user=ec2-user" \
              -var="ami=${{ inputs.ami }}" \
              -var="arc=amd64" \
              -var="binary_name=amazon-cloudwatch-agent.rpm" \
              -var="s3_bucket=${S3_INTEGRATION_BUCKET}" \
              -var="ssh_key_name=${KEY_NAME}" \
              -var="test_dir=./test/efa_ec2" ; then terraform destroy -auto-approve
            else
              terraform destroy -auto-approve && exit 1
            fi

      #This is here just in case workflow cancel
      - name: Terraform destroy
        if: ${{ cancelled() || failure() }}
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          max_attempts: 3
          timeout_minutes: 8
          retry_wait_seconds: 5
          command: cd terraform/ec2/efa && terraform destroy --auto-approve
