# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Reusable EKS E2E Test

env:
  TERRAFORM_AWS_ASSUME_ROLE_DURATION: 14400 # 4 hours

on:
  workflow_call:
    inputs:
      terraform_dir:
        required: true
        type: string
      job_id:
        required: true
        type: string
      test_props:
        required: true
        type: string
      test_repo_name:
        required: true
        type: string
      test_repo_url:
        required: true
        type: string
      test_repo_branch:
        required: true
        type: string
      cloudwatch_agent_repository:
        required: true
        type: string
      cloudwatch_agent_tag:
        required: true
        type: string
      cloudwatch_agent_operator_repository:
        required: true
        type: string
      cloudwatch_agent_target_allocator_repository:
        required: false
        type: string
      cloudwatch_agent_operator_tag:
        required: true
        type: string
      region:
        required: true
        type: string
      helm_charts_branch:
        required: true
        type: string
      terraform_assume_role:
        required: true
        type: string
      agent_config:
        required: true
        type: string
      prometheus_config:
        required: false
        type: string
        default: ""
      otel_config:
        required: false
        type: string
        default: ""
      sample_app:
        required: true
        type: string
      eks_installation_type:
        required: true
        type: string
      ip_family:
        required: false
        type: string
        default: "ipv4"
      vpc_name:
        required: false
        type: string
        default: ""

jobs:
  EKSE2ETest:
    name: 'EKSE2ETest'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arrays: ${{ fromJson(inputs.test_props) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: ${{inputs.test_repo_name}}
          ref: ${{inputs.test_repo_branch}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ inputs.terraform_assume_role }}
          aws-region: ${{ inputs.region }}
          role-duration-seconds: ${{ env.TERRAFORM_AWS_ASSUME_ROLE_DURATION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.12.0

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform apply
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        env:
          INPUT_TERRAFORM_DIR: ${{ inputs.terraform_dir }}
          INPUT_REGION: ${{ inputs.region }}
          MATRIX_K8S_VERSION: ${{ matrix.arrays.k8sVersion }}
          MATRIX_NODES: ${{ matrix.arrays.nodes }}
          MATRIX_TEST_DIR: ${{ matrix.arrays.test_dir }}
          INPUT_HELM_CHARTS_BRANCH: ${{ inputs.helm_charts_branch }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          INPUT_AGENT_REPO: ${{ inputs.cloudwatch_agent_repository }}
          INPUT_AGENT_TAG: ${{ inputs.cloudwatch_agent_tag }}
          INPUT_OPERATOR_REPO: ${{ inputs.cloudwatch_agent_operator_repository }}
          INPUT_OPERATOR_TAG: ${{ inputs.cloudwatch_agent_operator_tag }}
          INPUT_TA_REPO: ${{ inputs.cloudwatch_agent_target_allocator_repository }}
          INPUT_AGENT_CONFIG: ${{ inputs.agent_config }}
          INPUT_PROMETHEUS_CONFIG: ${{ inputs.prometheus_config }}
          INPUT_OTEL_CONFIG: ${{ inputs.otel_config }}
          INPUT_SAMPLE_APP: ${{ inputs.sample_app }}
          INPUT_EKS_INSTALLATION_TYPE: ${{ inputs.eks_installation_type }}
          INPUT_IP_FAMILY: ${{ inputs.ip_family }}
          INPUT_VPC_NAME: ${{ inputs.vpc_name }}
        with:
          max_attempts: 3
          timeout_minutes: 60
          retry_wait_seconds: 5
          command: |
            if [ -n "$INPUT_TERRAFORM_DIR" ]; then
              cd "$INPUT_TERRAFORM_DIR"
            else
              cd terraform/eks/e2e
            fi

            terraform init
            if terraform apply --auto-approve \
              -var="region=$INPUT_REGION" \
              -var="k8s_version=$MATRIX_K8S_VERSION" \
              -var="nodes=$MATRIX_NODES" \
              -var="helm_charts_branch=$INPUT_HELM_CHARTS_BRANCH" \
              -var="cloudwatch_agent_repository_url=$ECR_REGISTRY" \
              -var="cloudwatch_agent_repository=$INPUT_AGENT_REPO" \
              -var="cloudwatch_agent_tag=$INPUT_AGENT_TAG" \
              -var="cloudwatch_agent_operator_repository_url=$ECR_REGISTRY" \
              -var="cloudwatch_agent_operator_repository=$INPUT_OPERATOR_REPO" \
              -var="cloudwatch_agent_operator_tag=$INPUT_OPERATOR_TAG" \
              -var="cloudwatch_agent_target_allocator_repository_url=$ECR_REGISTRY" \
              -var="cloudwatch_agent_target_allocator_repository=$INPUT_TA_REPO" \
              -var="cloudwatch_agent_target_allocator_tag=$INPUT_OPERATOR_TAG" \
              -var="test_dir=$MATRIX_TEST_DIR" \
              -var="agent_config=$INPUT_AGENT_CONFIG" \
              -var="prometheus_config=$INPUT_PROMETHEUS_CONFIG" \
              -var="otel_config=$INPUT_OTEL_CONFIG" \
              -var="sample_app=$INPUT_SAMPLE_APP" \
              -var="eks_installation_type=$INPUT_EKS_INSTALLATION_TYPE" \
              -var="ip_family=$INPUT_IP_FAMILY" \
              -var="vpc_name=$INPUT_VPC_NAME"; then
              terraform destroy --auto-approve
            else
              terraform destroy --auto-approve && exit 1
            fi

      - name: Terraform destroy
        if: ${{ cancelled() || failure() }}
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        env:
          INPUT_TERRAFORM_DIR: ${{ inputs.terraform_dir }}
        with:
          max_attempts: 3
          timeout_minutes: 8
          retry_wait_seconds: 5
          command: |
            if [ -n "$INPUT_TERRAFORM_DIR" ]; then
              cd "$INPUT_TERRAFORM_DIR"
            else
              cd terraform/eks/e2e
            fi
            terraform destroy --auto-approve
