# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: C/D

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the version number to release'
        required: true
      sha:
        description: 'the github sha to release'
        required: true

jobs:
  release-to-github:
    runs-on: ubuntu-latest
    needs: [ validation-tests-checked, release-checking, clean-ssm-package]
    if: ${{ always() && needs.validation-tests-checked.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Generate release-note
        run: sh tools/release/generate-release-note.sh

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.release-checking.outputs.version }}
          commitish: ${{ github.event.inputs.sha }}
          release_name: ${{ needs.release-checking.outputs.version }}
          body_path: release-note
          draft: true
          prerelease: true

