# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Generate GitHub's release note

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the version number to release'
        required: true
      sha:
        description: 'the github sha to release'
        required: true

jobs:
  release-note-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Generate release-note
        run: VERSION=${{ github.event.inputs.version }} bash tools/release/image-binary-release/s3-release.sh

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          commitish: ${{ github.event.inputs.sha }}
          release_name: ${{ github.event.inputs.version }}
          body_path: release-note
          draft: true
          prerelease: true

