# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

# @TODO delete this when we remove the internal cw agent integration pipeline
name: Dedicated Host Daily Resources Cleaner

on:
  schedule:
    - cron: "0 0 * * *" # Run Every Day At Midnight
  workflow_dispatch:

jobs:
  clean-dedicated-hosts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.INTERNAL_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Clean old dedicated host
        run: go run ./integration/clean/clean_dedicated_host/clean_dedicated_host.go --tags=clean