name: Pre-merge Workflow Check
on:
  workflow_run:
    workflows: ["PR Build", "pr build"]
    types:
      - completed
      - requested

jobs:
  log-workflow-id:
    name: Log Workflow ID
    runs-on: ubuntu-latest
    steps:
      - name: Log Workflow ID
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"

  check-pr-test-workflow:
    name: Check PR Test Success
    runs-on: ubuntu-latest
    needs: log-workflow-id
    steps:
      - name: Check PR Test Workflow Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Get workflow run details
          workflow_run=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$WORKFLOW_RUN_ID")

          # Get associated PRs
          pull_requests=$(echo "$workflow_run" | jq -r '.pull_requests')
          if [ "$pull_requests" == "[]" ] || [ -z "$pull_requests" ]; then
            echo "No PR associated with this workflow run"
            exit 0
          fi

          # Get PR number
          pr_number=$(echo "$pull_requests" | jq -r '.[0].number')
          echo "Checking workflow results for PR #$pr_number"

          # Check workflow conclusion
          conclusion=$(echo "$workflow_run" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "PR Test workflow for PR #$pr_number did not complete successfully"
            exit 0
          fi

          # Get jobs for the workflow run
          jobs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$WORKFLOW_RUN_ID/jobs")

          # Check required jobs
          required_jobs=("changes" "lint")
          for job_name in "${required_jobs[@]}"; do
            job_status=$(echo "$jobs" | jq -r ".jobs[] | select(.name == \"$job_name\") | .conclusion")
            if [ "$job_status" != "success" ]; then
              echo "Required job $job_name has not completed successfully for PR #$pr_number"
              exit 0
            fi
          done

          echo "All required workflow jobs completed successfully for PR #$pr_number"