name: Pre-merge Workflow Check

on:
  workflow_run:
    workflows: ["PR Build", "pr build"]
    types:
      - completed
      - requested

jobs:
  check-pr-test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Test Workflow Status
        uses: actions/github-script@v6
        with:
          script: |
            const workflowRun = context.payload.workflow_run;

            const pullRequests = workflowRun.pull_requests;
            if (!pullRequests || pullRequests.length === 0) {
              console.log('No PR associated with this workflow run');
              return;
            }

            const originalPR = pullRequests[0];

            const currentPR = context.payload.workflow_run.head_repository.owner.login === context.repo.owner &&
                            context.payload.workflow_run.head_repository.name === context.repo.repo
                            ? await github.rest.pulls.get({
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                pull_number: originalPR.number
                              })
                            : null;

            if (!currentPR) {
              console.log('Could not determine current PR context');
              return;
            }

            if (currentPR.data.number !== originalPR.number) {
              console.log(`PR mismatch: Original PR #${originalPR.number} vs Current PR #${currentPR.data.number}`);
              return;
            }

            console.log(`Checking workflow results for PR #${originalPR.number}`);

            if (workflowRun.conclusion !== 'success') {
              console.log(`PR Test workflow for PR #${originalPR.number} did not complete successfully`);
              return;
            }

            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: workflowRun.id
            });

            const requiredJobs = [
              'changes',
              'lint'
            ];

            for (const job of jobs.data.jobs) {
              if (requiredJobs.includes(job.name) && job.conclusion !== 'success') {
                console.log(`Required job ${job.name} has not completed successfully for PR #${originalPR.number}`);
                return;
              }
            }

            console.log(`All required workflow jobs completed successfully for PR #${originalPR.number}`);