name: Pre-merge Workflow Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main*
      - feature*
      - tjstark/**

jobs:
  verify-pr-build:
    name: Verify PR Build Status
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Build Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Get workflow runs for this PR
          workflow_runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs?event=pull_request&head_sha=${{ github.event.pull_request.head.sha }}")

          # Look for PR Build workflow
          pr_build=$(echo "$workflow_runs" | jq -r '.workflow_runs[] | select(.name == "PR Build" and .head_sha == "${{ github.event.pull_request.head.sha }}")')

          if [ -z "$pr_build" ]; then
            echo "No PR Build workflow found for this commit"
            exit 1
          fi

          # Check status
          status=$(echo "$pr_build" | jq -r '.status')
          conclusion=$(echo "$pr_build" | jq -r '.conclusion')

          if [ "$status" == "in_progress" ]; then
            echo "PR Build workflow is still running. Waiting for completion..."
            exit 1
          elif [ "$status" == "completed" ] && [ "$conclusion" != "success" ]; then
            echo "PR Build workflow failed with conclusion: $conclusion"
            exit 1
          elif [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
            echo "PR Build workflow completed successfully"
          else
            echo "Unexpected workflow status: $status"
            exit 1
          fi

  # Add this job to handle rerunning
  wait-for-build:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Wait and Retry
        run: |
          echo "PR Build is in progress or failed. This check will automatically re-run when the build completes."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
