# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Build And Upload Docker Image
env:
  CWA_GITHUB_TEST_REPO_NAME: "aws/amazon-cloudwatch-agent-test"

on:
  workflow_dispatch:
    inputs:
      ContainerRepositoryNameAndTag:
        description: "ECR repo name and tag"
        required: true
        type: string
      BucketKey:
        description: "S3 URI to upload artifacts into."
        required: true
        type: string
      PackageBucketKey:
        description: "Integration tests put the MSI and PKG in a different bucket path than the binaries."
        required: true
        type: string
  workflow_call:
    inputs:
      ContainerRepositoryNameAndTag:
        description: "ECR repo name and tag"
        required: true
        type: string
      BucketKey:
        description: "S3 URI to upload artifacts into."
        required: true
        type: string
      PackageBucketKey:
        description: "Integration tests put the MSI and PKG in a different bucket path than the binaries."
        required: true
        type: string

jobs:
  MakeBinary:
    name: 'MakeBinary'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Free up disk space
        run: .github/scripts/free-disk-space.sh

      - name: Cache container
        id: cached_container
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          key: "cached_container_${{ github.sha }}"
          path: go.mod

      - name: Login ECR
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1

      - name: Set up Docker Buildx
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Set up QEMU
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Copy Binary For Agent Image Build
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        run: |
          mkdir amd64
          mkdir arm64
          aws s3 cp s3://${{ vars.S3_INTEGRATION_BUCKET }}/${{ inputs.BucketKey }}/linux/amd64/amazon-cloudwatch-agent.rpm amd64/amazon-cloudwatch-agent.rpm
          aws s3 cp s3://${{ vars.S3_INTEGRATION_BUCKET }}/${{ inputs.BucketKey }}/linux/arm64/amazon-cloudwatch-agent.rpm arm64/amazon-cloudwatch-agent.rpm

      - name: Get ECR Repo name
        id: repo_name
        env:
          ContainerRepositoryNameAndTag: ${{ inputs.ContainerRepositoryNameAndTag }}
        run: |
          RepoName=`echo $ContainerRepositoryNameAndTag | awk -F: '{print $1}'`
          echo "::set-output name=ContainerRepositoryName::$RepoName"

      - name: Build Cloudwatch Agent Image amd64
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        with:
          file: amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/localal2/Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ steps.repo_name.outputs.ContainerRepositoryName }}:linux-amd64
          platforms: linux/amd64
          provenance: false

      - name: Build Cloudwatch Agent Image arm64
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_container.outputs.cache-hit == false
        with:
          file: amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/localal2/Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ steps.repo_name.outputs.ContainerRepositoryName }}:linux-arm64
          platforms: linux/arm64
          provenance: false

  CreateContainerManifest:
    name: 'CreateManifest'
    needs: ['MakeBinary']
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Get ECR Repo name
        id: repo_name
        env:
          ContainerRepositoryNameAndTag: ${{ inputs.ContainerRepositoryNameAndTag }}
        run: |
          RepoName=`echo $ContainerRepositoryNameAndTag | awk -F: '{print $1}'`
          echo "::set-output name=ContainerRepositoryName::$RepoName"

      - name: Create manifest and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          OrigREPOSITORY: ${{ inputs.ContainerRepositoryNameAndTag }}
          REPOSITORY: ${{ steps.repo_name.outputs.ContainerRepositoryName }}
          REPOLinuxAmd: ${{ steps.repo_name.outputs.ContainerRepositoryName }}:linux-amd64
          REPOLinuxArm: ${{ steps.repo_name.outputs.ContainerRepositoryName }}:linux-arm64
        run: |
          docker manifest create $REGISTRY/$OrigREPOSITORY --amend $REGISTRY/$REPOLinuxAmd --amend $REGISTRY/$REPOLinuxArm
          docker manifest push $REGISTRY/$OrigREPOSITORY
