# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Test Release Candidate
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
  TERRAFORM_AWS_ASSUME_ROLE_DURATION: 14400 # 4 hours
  S3_INTEGRATION_BUCKET: ${{ vars.S3_INTEGRATION_BUCKET }}
  S3_RELEASE_BUCKET: amazon-cloud-watch-agent
  S3_RELEASE_REPO: cloudwatch-agent
  TERRAFORM_AWS_ASSUME_ROLE_ITAR: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE_ITAR }}
  S3_INTEGRATION_BUCKET_ITAR: ${{ vars.S3_INTEGRATION_BUCKET_ITAR }}
  TERRAFORM_AWS_ASSUME_ROLE_CN: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE_CN }}
  S3_INTEGRATION_BUCKET_CN: ${{ vars.S3_INTEGRATION_BUCKET_CN }}

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'The build ID (release candidate build number or GitHub commit SHA)'
        type: string
        required: true
      test_repo_branch:
        description: 'Override for the test repo branch (default is main)'
        type: string
  pull_request:

jobs:
  RepackageArtifacts:
    name: 'RepackageArtifacts'
    uses: ./.github/workflows/repackage-release-artifacts.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      build_id: ${{ inputs.build_id }}

  StartIntegrationTests:
    needs: [ RepackageArtifacts ]
    runs-on: ubuntu-latest
    steps:
      # Avoid the limit of 5 nested workflows by executing the workflow in this manner
      - run: gh workflow run test-artifacts.yml --ref ${{ github.ref_name }} --repo $GITHUB_REPOSITORY -f build_id=${{ inputs.build_id }} -f ecr_rest_repo=${{ env.S3_RELEASE_REPO }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
