# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Upload Dependencies to S3 (CN)

env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  KEY_NAME: ${{ secrets.KEY_NAME }}

on:
  workflow_call:
    inputs:
      region:
        type: string
      test_repo_name:
        required: true
        type: string
      test_repo_branch:
        required: true
        type: string
      test_repo_url:
        required: true
        type: string
      github_sha:
        required: true
        type: string
      s3_integration_bucket:
        required: true
        type: string
      terraform_assume_role:
        type: string

jobs:
  UploadDependenciesS3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.test_repo_name }}
          ref: ${{ inputs.test_repo_branch }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.terraform_assume_role }}
          aws-region: ${{ inputs.region }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
          aws s3 ls

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22.2

      - name: Run go mod vendor
        run: |
          go mod tidy
          go mod vendor

      - name: Upload vendor directory to S3
        run: |
          aws s3 sync ./vendor s3://${{ inputs.s3_integration_bucket }}/vendor/ --delete

